name: Release

on:
  push:
    tags:
      - 'v*' # Запускать при пуше тегов типа v1.0.0

permissions:
  contents: write

jobs:
  build-release:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: repomd
            asset_name: repomd-linux-amd64
          - os: windows-latest
            artifact_name: repomd.exe
            asset_name: repomd-windows-amd64.exe
          - os: macos-latest
            artifact_name: repomd
            asset_name: repomd-macos-arm64

    steps:
      - uses: actions/checkout@v6

      - name: Verify version
        shell: bash
        run: test "v$(cargo metadata --no-deps --format-version 1 | sed -n 's/.*\"version\":\"\([^\"]*\)\".*/\1/p')" = "${GITHUB_REF_NAME}"

      - name: Test
        run: cargo test --all-targets --locked

      - name: Build binary
        run: cargo build --release --locked

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
